---
services:
  dme:
    image: jcostom/dme-update:latest
    container_name: dme
    volumes:
      - /var/docks/dme:/config
    user: 1000:1000
    environment:
      - APIKEY=dns-made-easy-api-key
      - SECRETKEY=dns-made-easy-secret-key
      - DMEZONEID=dns-made-easy-zone-id-number
      - RECORDS=list,of,hostnames,you,are,updating
      - USETELEGRAM=[0|1]
      - CHATID='Your Telegram Chat ID'
      - MYTOKEN='Your Telegram Bot Token'
      - SITENAME='Your Site Identifier'
      - TZ=America/New_York # or whatever makes sense for you
    restart: unless-stopped
    network_mode: bridge
